{% set name = "papis" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/papis-{{ version }}.tar.gz
  sha256: f35a6aa938361bb67c5b77d916ac8cec587638ad7d86dc87a917ac608ec965a7

build:
  entry_points:
    - papis=papis.commands.default:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - pyyaml >=3.12
    - arxiv2bib >=1.0.7
    - beautifulsoup4 >=4.4.1
    - bibtexparser <1.4.0
    - chardet >=3.0.2
    - click >=7.0.0
    - colorama >=0.2
    - dominate
    - filetype >=1.0.1
    - habanero <1.2.0 
    - isbnlib >=3.9.1
    - lxml <=4.9.1
    - prompt_toolkit >=2.0.5
    - pygments >=2.2.0
    - pyparsing >=2.2.0
    - python-doi >=0.1.1
    - python-slugify >=1.2.6
    - requests >=2.11.1
    - stevedore >=1.30
    - tqdm >=4.1
    - twine <5.0.0,>=4.0.1  # isbnlib 3.10.13 has requirement twine<5.0.0,>=4.0.1
    - typing-extensions >=3.7

test:
  imports:
    - papis
  commands:
    - pip check
    - papis --help
  requires:
    - pip

about:
  home: https://github.com/papis/papis
  summary: Powerful and highly extensible command-line based document and bibliography manager
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
