schema_version: 1

context:
  name: papis
  version: 0.16.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/papis-${{ version }}.tar.gz
  sha256: a7ce419077bf50bd1db14618c0be971f325a0f331632d4729d5acf8239053c74

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - papis=papis.commands.default:run

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - hatchling
  run:
    - arxiv >=1.0.0
    - platformdirs >=4.0.0
    - prompt-toolkit >=3.0.5
    - python >=${{ python_min }}
    - pyyaml >=3.12
    - beautifulsoup4 >=4.4.1
    - bibtexparser >=0.6.2,<2
    - click >=7
    - colorama >=0.2
    - dominate >=2.8
    - filetype >=1.0.1
    - habanero >=0.6
    - lxml >=4.3.5
    - pygments >=2.2
    - python-doi >=0.1.1
    - python-slugify >=1.2.6
    - requests >=2.11.1
    - lark >=1.2.0
tests:
  - python:
      imports:
        - papis
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - papis --help

about:
  summary: Powerful and highly extensible command-line based document and bibliography manager
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/papis/papis

extra:
  recipe-maintainers:
    - jan-janssen
